export enum EntryAllListTypes {
  ENTRY_ALL_LIST_LOAD = 'ENTRY_ALL_LIST_LOAD',
  ENTRY_ALL_LIST_RELOAD = 'ENTRY_ALL_LIST_RELOAD',
  ENTRY_ALL_LIST_ITEM_ADD = 'ENTRY_MY_ITEM_ADD',
  ENTRY_ALL_LIST_ITEM_UPDATE = 'ENTRY_ALL_LIST_ITEM_UPDATE',
  ENTRY_ALL_LIST_ITEM_REMOVE = 'ENTRY_ALL_LIST_ITEM_REMOVE',
  ENTRY_ALL_LIST_SET_FILTERS = 'ENTRY_ALL_LIST_SET_FILTERS'
}
